<?xml version="1.0" encoding="utf-8"?><Database Name="DBEmployee" Class="LinQModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=300VONGNT-W710;Initial Catalog=DBEmployee;Integrated Security=True" SettingsObjectName="MockupProject_K30_DotNet.Properties.Settings" SettingsPropertyName="DBEmployeeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FSU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>